asobi/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('games.urls', namespace='games'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

games/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import *

app_name = 'games'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('profile/', login_required(ProfileView.as_view()), name='my_profile'),
    path('profile/<str:username>/', ProfileView.as_view(), name='user_profile'),
    path('games/<str:game_type>/', login_required(GameListView.as_view()), name='my_games_list'),
    path('games/<str:game_type>/<str:username>/', GameListView.as_view(), name='user_games_list'),

    path('tictactoe/', TicTacToeView.as_view(), name='tictactoe'),
    path('obstruction/', ObstructionView.as_view(), name='obstruction'),
    path('ludo/', LudoView.as_view(), name='ludo'),
    path('battleship/', BattleshipView.as_view(), name='battleship'),
    path('connect4/', Connect4View.as_view(), name='connect4'),
    path('othello/', OthelloView.as_view(), name='othello'),

    path('current-user/', CurrentUserView.as_view()),

    path('tictactoe-from-code/<str:game_code>/', TicTacToeViewSet.as_view()),
    path('obstruction-from-code/<str:game_code>/', ObstructionViewSet.as_view()),
    path('ludo-from-code/<str:game_code>/', LudoViewSet.as_view()),
    path('battleship-from-code/<str:game_code>/', BattleshipViewset.as_view()),
    path('connect4-from-code/<str:game_code>/', Connect4Viewset.as_view()),
    path('othello-from-code/<str:game_code>/', OthelloViewset.as_view()),
]

games/views/api_views.py
from django.http import Http404
from rest_framework.views import APIView
from rest_framework.response import Response
from games.serializers import *


class CurrentUserView(APIView):
    @staticmethod
    def get(request):
        serializer = UserSerializer(request.user)
        return Response(serializer.data)


class ClaimingGameViewSet(APIView):
    def __init__(self, game_model, game_serializer, square_serializer):
        super(ClaimingGameViewSet, self).__init__()
        self.game_model = game_model
        self.game_serializer = game_serializer
        self.square_serializer = square_serializer

    # _ is request
    def get(self, _, **kwargs):
        game = self.game_model.get_by_code(kwargs['game_code'])
        if game is None:
            raise Http404
        squares = game.get_all_squares()
        game_serializer = self.game_serializer(game)
        square_serializer = self.square_serializer(squares, many=True)
        return_data = {'game': game_serializer.data,
                       'squares': square_serializer.data}
        return Response(return_data)


class TicTacToeViewSet(ClaimingGameViewSet):
    def __init__(self):
        super(TicTacToeViewSet, self).__init__(
            game_model=TicTacToeGame,
            game_serializer=TicTacToeSerializer,
            square_serializer=TicTacToeSquareSerializer
        )


class ObstructionViewSet(ClaimingGameViewSet):
    def __init__(self):
        super(ObstructionViewSet, self).__init__(
            game_model=ObstructionGame,
            game_serializer=ObstructionSerializer,
            square_serializer=ObstructionSquareSerializer
        )


class LudoViewSet(APIView):
    # _ is request
    @staticmethod
    def get(_, **kwargs):
        game = LudoGame.get_by_code(kwargs['game_code'])
        if game is None:
            raise Http404
        players = game.get_all_players()
        pieces = game.get_all_pieces()
        game_serializer = LudoGameSerializer(game)
        player_serializer = LudoPlayerSerializer(players, many=True)
        piece_serializer = LudoPieceSerializer(pieces, many=True)
        return_data = {'game': game_serializer.data,
                       'players': player_serializer.data,
                       'pieces': piece_serializer.data}
        return Response(return_data)


class BattleshipViewset(APIView):
    # _ is request
    @staticmethod
    def get(_, **kwargs):
        game = BattleshipGame.get_by_code(kwargs['game_code'])
        if game is None:
            raise Http404
        creator_squares = game.get_creator_squares()
        opponent_squares = game.get_opponent_squares()
        game_serializer = BattleshipSerializer(game)
        creator_square_serializer = BattleshipSquareSerializer(creator_squares, many=True)
        opponent_square_serializer = BattleshipSquareSerializer(opponent_squares, many=True)
        data = {
            'game': game_serializer.data,
            'creator_squares': creator_square_serializer.data,
            'opponent_squares': opponent_square_serializer.data
        }
        return Response(data)


class Connect4Viewset(APIView):
    # _ is request
    @staticmethod
    def get(_, **kwargs):
        game = Connect4Game.get_by_code(kwargs['game_code'])
        if game is None:
            raise Http404
        squares = game.get_all_squares()
        game_serializer = Connect4Serializer(game)
        square_serializer = Connect4SquareSerializer(squares, many=True)
        data = {
            'game': game_serializer.data,
            'squares': square_serializer.data
        }
        return Response(data)


class OthelloViewset(APIView):
    # _ is request
    @staticmethod
    def get(_, **kwargs):
        game = OthelloGame.get_by_code(kwargs['game_code'])
        if game is None:
            raise Http404
        squares = game.get_all_squares()
        game_serializer = OthelloSerializer(game)
        square_serializer = OthelloSquareSerializer(squares, many=True)
        data = {
            'game': game_serializer.data,
            'squares': square_serializer.data
        }
        return Response(data)

games/views/user_views.py
from django.shortcuts import render
from django.http import Http404
from django.views import View
from django.core.paginator import Paginator
from games.models import *


GAMES = {
    'tictactoe': (TicTacToeGame, 'Tic-Tac-Toe', 'img/logos/tictactoe.png'),
    'obstruction': (ObstructionGame, 'Obstruction', 'img/logos/obstruction.png'),
    'ludo': (LudoGame, 'Ludo', 'img/logos/ludo.png'),
    'battleship': (BattleshipGame, 'Battleship', 'img/logos/battleship.png'),
    'connect4': (Connect4Game, 'Connect Four', 'img/logos/connect4.png'),
    'othello': (OthelloGame, 'Othello', 'img/logos/othello.png'),
}


def get_user_from_username(username, request):
    user = None
    if username is None:
        if request.user.is_authenticated:
            user = request.user
    else:
        user = User.objects.filter(username=username)
        if user:
            user = user[0]
    return user


def get_games(game_model, user, last_n=None):
    if hasattr(game_model, 'opponent'):
        q1 = Q(creator=user)
        q2 = Q(opponent=user)
        games = game_model.objects.filter(q1 | q2).order_by('-id')
    else:
        user_players = game_model.PLAYER_MODEL.objects.filter(user=user).order_by('-id')
        games = [player.game for player in user_players]
    return games[:last_n] if last_n else games


def get_games_data(games, user, game_type):
    result = []
    for game in games:
        players = game.get_all_players()
        if not players:
            opponent = game.opponent if game.creator == user else game.creator
            players = [opponent] if opponent is not None else []
        else:
            players = [player.user.username for player in players if player.user != user]
        game_data = {
            'game': game,
            'players': players,
            'url': f"/{game_type}/?gc={game.game_code}",
        }
        result.append(game_data)
    return result


class ProfileView(View):
    LAST_N = 5
    template_name = 'profile.html'

    def get(self, request, username=None):
        user = get_user_from_username(username, request)
        if not user:
            raise Http404
        all_games_data = []
        for game_type, values in GAMES.items():
            game_model, display_name, logo = values
            last_n_games = get_games(game_model, user, self.LAST_N)
            game_model_data = get_games_data(last_n_games, user, game_type)
            all_games_data.append({
                'game_type': game_type,
                'display_name': display_name,
                'logo': logo,
                'page_url': f"games:{game_type}",
                'game_model_data': game_model_data,
            })
        context = {'profile_user': user, 'all_games_data': all_games_data}
        return render(request, self.template_name, context)


class GameListView(View):
    PER_PAGE = 25
    template_name = 'games_list.html'

    def get(self, request, game_type=None, username=None):
        if game_type not in GAMES:
            raise Http404
        user = get_user_from_username(username, request)
        if not user:
            raise Http404
        game_model, display_name, logo = GAMES[game_type]
        games = get_games(game_model, user)
        game_model_data = get_games_data(games, user, game_type)
        paginator = Paginator(game_model_data, self.PER_PAGE)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context = {
            'profile_user': user,
            'display_name': display_name,
            'logo': logo,
            'page_url': f"games:{game_type}",
            'page_obj': page_obj
        }
        return render(request, self.template_name, context)

games/views/views.py
import re
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import QueryDict
from django.contrib import messages
from django.views import View
from games.forms import *


class GameContext:
    def __init__(self, name, url, image, banner=None):
        self.name = name
        self.url = url
        self.image = image
        self.banner = banner


class Home(View):
    template_name = 'home.html'
    MOBILE_AGENT_RE = re.compile(r".*(iphone|mobile|androidtouch)", re.IGNORECASE)

    def is_mobile(self, request):
        return self.MOBILE_AGENT_RE.match(request.META['HTTP_USER_AGENT'])

    def get(self, request):
        is_mobile = self.is_mobile(request)
        ttt_obj = GameContext(
            name='Tic-Tac-Toe',
            url='games:tictactoe',
            image='img/logos/tictactoe.png',
            banner={
                'image': 'img/banners/tictactoe.png' if not is_mobile else 'img/banners/mobile/tictactoe.png',
                'description': 'Probably the most popular pen-and-paper game!'
            })
        obs_obj = GameContext(
            name='Obstruction',
            url='games:obstruction',
            image='img/logos/obstruction.png',
            banner={
                'image': 'img/banners/obstruction.png' if not is_mobile else 'img/banners/mobile/obstruction.png',
                'description': "Don't let your opponent have the last move!"
            })
        ludo_obj = GameContext(
            name='Ludo',
            url='games:ludo',
            image='img/logos/ludo.png',
            banner={
                'image': 'img/banners/ludo.png' if not is_mobile else 'img/banners/mobile/ludo.png',
                'description': 'Race to the finish before others can!'
            }
        )
        battleship_obj = GameContext(
            name='Battleship',
            url='games:battleship',
            image='img/logos/battleship.png',
            banner={
                'image': 'img/banners/battleship.png' if not is_mobile else 'img/banners/mobile/battleship.png',
                'description': "Destroy the enemy fleet before they destroy yours!"
            }
        )
        connect4_obj = GameContext(
            name='Connect Four',
            url='games:connect4',
            image='img/logos/connect4.png',
            banner={
                'image': 'img/banners/connect4.png' if not is_mobile else 'img/banners/mobile/connect4.png',
                'description': 'Connect four in a row before your opponent does!'
            }
        )
        othello_obj = GameContext(
            name='Othello',
            url='games:othello',
            image='img/logos/othello.png',
            banner={
                'image': 'img/banners/othello.png' if not is_mobile else 'img/banners/mobile/othello.png',
                'description': 'A minute to learn, a lifetime to master!'
            }

        )

        context = dict(games=[ttt_obj, obs_obj, ludo_obj, battleship_obj, connect4_obj, othello_obj])

        return render(request, self.template_name, context)


@method_decorator(login_required, name='get')
class GameView(View):
    # All other variables are initialized in child views
    gc = None
    rules_template = None

    def game_redirect(self, request):
        response = redirect(self.page)
        q = QueryDict(mutable=True)
        q['gc'] = self.gc
        response['Location'] += f"?{q.urlencode()}"
        messages.success(request, f"Created new game: {self.gc}")
        return response

    @staticmethod
    def game_obj_operation(request, game_obj):
        if (game_obj.opponent is None) and (game_obj.creator != request.user):
            game_obj.set_opponent(request.user)

    def get(self, request):
        self.gc = request.GET.get('gc')
        context = {'form': self.form_class(), 'rules_template': self.rules_template}
        if self.gc == '':
            # This method is different for all child views, so it is defined later
            self.create_new_game(request)
            return self.game_redirect(request)
        if self.gc:
            try:
                game_obj = self.game_model.objects.get(game_code=self.gc)
                self.game_obj_operation(request, game_obj)
            except self.game_model.DoesNotExist:
                messages.error(request, "No valid game code provided")
                return redirect(self.page)
            context = {'gc': self.gc}
        return render(request, self.template_name, context)


class TicTacToeView(GameView):
    template_name = 'tictactoe.html'
    form_class = StartTicTacToeForm
    game_model = TicTacToeGame
    page = 'games:tictactoe'
    rules_template = 'rules/tictactoe.html'

    def create_new_game(self, request):
        n = request.GET.get('n')
        n = TicTacToeGame.default_n if (n is None) or (n == '') else int(n)
        game = TicTacToeGame.create_new(user=request.user, n=n)
        self.gc = game.game_code


class ObstructionView(GameView):
    template_name = 'obstruction.html'
    form_class = StartObstructionForm
    game_model = ObstructionGame
    page = 'games:obstruction'
    rules_template = 'rules/obstruction.html'

    def create_new_game(self, request):
        rows = request.GET.get('row')
        cols = request.GET.get('col')
        def calc(x): return ObstructionGame.default_n if (x is None) or (x == '') else int(x)
        rows = calc(rows)
        cols = calc(cols)
        game = ObstructionGame.create_new(user=request.user, rows=rows, cols=cols)
        self.gc = game.game_code


class LudoView(GameView):
    template_name = 'ludo.html'
    form_class = StartLudoForm
    game_model = LudoGame
    page = 'games:ludo'
    rules_template = 'rules/ludo.html'

    def create_new_game(self, request):
        players = request.GET.get('players')
        players = 4 if (players is None) or (players == '') else players
        game = LudoGame.create_new(user=request.user, players=players)
        self.gc = game.game_code

    @staticmethod
    def game_obj_operation(request, game_obj):
        game_obj.add_player(request.user)


class BattleshipView(GameView):
    template_name = 'battleship.html'
    form_class = StartBattleShipForm
    game_model = BattleshipGame
    page = 'games:battleship'
    rules_template = 'rules/battleship.html'

    def create_new_game(self, request):
        game = BattleshipGame.create_new(user=request.user)
        self.gc = game.game_code


class Connect4View(GameView):
    template_name = 'connect4.html'
    form_class = StartConnect4Form
    game_model = Connect4Game
    page = 'games:connect4'
    rules_template = 'rules/connect4.html'
    SIZES = {
        '7x6': (7, 6),
        '5x4': (5, 4),
        '6x5': (6, 5),
        '8x7': (8, 7),
        '9x7': (9, 7),
        '10x7': (10, 7),
        '8x8': (8, 8)
    }

    def create_new_game(self, request):
        size = request.GET.get('size')
        size = self.SIZES[size] if size in self.SIZES else (7, 6)
        game = Connect4Game.create_new(user=request.user, size=size)
        self.gc = game.game_code


class OthelloView(GameView):
    template_name = 'othello.html'
    form_class = StartOthelloForm
    game_model = OthelloGame
    page = 'games:othello'
    rules_template = 'rules/othello.html'

    def create_new_game(self, request):
        game = OthelloGame.create_new(user=request.user)
        self.gc = game.game_code

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link rel="shortcut icon" type="image/png" href="{% static 'img/logos/favicon.ico' %}"/>

  <title>{% block head_title %}Asobi{% endblock %}</title>
  <script>
      $(function () {
          $('[data-toggle="tooltip"]').tooltip()
      })
  </script>
  {% block extra_head %}
  {% endblock %}
</head>

<body>
  {% block navbar %}
  <nav class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand ms-2" href="{% url 'games:home' %}">
      <img height="30px" src="{% static 'img/logos/asobi_title.png' %}">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#base-navbar" aria-controls="base-navbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="base-navbar">
      <ul class="navbar-nav">
        <li class="nav-item active">
          {% url 'games:home' as url %}
          <a class="nav-link {% if request.path == url %} active {% endif %}" href="{{ url }}">
            Home
          </a>
          <div class="underline"></div>
        </li>
        <li class="nav-item active">
          {% url 'games:about' as url %}
          <a class="nav-link {% if request.path == url %} active {% endif %}" href="{{ url }}">
            About
          </a>
          <div class="underline"></div>
        </li>
        <li class="nav-item active">
          {% url 'games:tictactoe' as url %}
          <a class="nav-link {% if request.path == url %} active {% endif %}" href="{{ url }}">
            Tic-Tac-Toe
          </a>
          <div class="underline"></div>
        </li>
        <li class="nav-item active">
          {% url 'games:obstruction' as url %}
          <a class="nav-link {% if request.path == url %} active {% endif %}" href="{{ url }}">
            Obstruction
          </a>
          <div class="underline"></div>
        </li>
        <li class="nav-item active">
          {% url 'games:ludo' as url %}
          <a class="nav-link {% if request.path == url %} active {% endif %}" href="{{ url }}">
            Ludo
          </a>
          <div class="underline"></div>
        </li>
        <li class="nav-item active">
          {% url 'games:battleship' as url %}
          <a class="nav-link {% if request.path == url %} active {% endif %}" href="{{ url }}">
            Battleship
          </a>
          <div class="underline"></div>
        </li>
        <li class="nav-item active">
          {% url 'games:connect4' as url %}
          <a class="nav-link {% if request.path == url %} active {% endif %}" href="{{ url }}">
            Connect Four
          </a>
          <div class="underline"></div>
        </li>
        <li class="nav-item active">
          {% url 'games:othello' as url %}
          <a class="nav-link {% if request.path == url %} active {% endif %}" href="{{ url }}">
            Othello
          </a>
          <div class="underline"></div>
        </li>
        {% if user.is_authenticated%}
        <li class="nav-item dropdown navbar-end">
          <a class="nav-link dropdown-toggle" href="{% url 'account_login' %}" id="signedin" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ user.username }}
          </a>
          <div class="underline"></div>
          <div class="dropdown-menu shadow" aria-labelledby="signedin">
            <a class="dropdown-item" href="{% url 'account_login' %}">Profile</a>
            <a class="dropdown-item" href="{% url 'games:my_games_list' game_type='tictactoe' %}">Tic-Tac-Toe games</a>
            <a class="dropdown-item" href="{% url 'games:my_games_list' game_type='obstruction' %}">Obstruction games</a>
            <a class="dropdown-item" href="{% url 'games:my_games_list' game_type='ludo' %}">Ludo games</a>
            <a class="dropdown-item" href="{% url 'games:my_games_list' game_type='battleship' %}">Battleship games</a>
            <a class="dropdown-item" href="{% url 'games:my_games_list' game_type='connect4' %}">Connect Four games</a>
            <a class="dropdown-item" href="{% url 'games:my_games_list' game_type='othello' %}">Othello games</a>
            <div class="divider mt-2 mb-2"></div>
            <a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a>
          </div>
        </li>
        {% else %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="{% url 'account_login' %}" id="notsignedin" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Sign in
          </a>
          <div class="underline"></div>
          <div class="dropdown-menu" aria-labelledby="notsignedin">
            <a class="dropdown-item" href="{% url 'account_login' %}">Login</a>
            <a class="dropdown-item" href="{% url 'account_signup' %}">Sign up</a>
          </div>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  {% if messages %}
  <div class="row w-100 text-center m-0 p-0">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissable m-0 p-0" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      {{ message }}
    </div>
    {% endfor %}
  </div>
  {% endif %}
  {% endblock %}
  {% block page_heading_wrapper %}
  <div class="page-heading">
    <h1>{% block page_heading %}{% endblock %}</h1>
  </div>
  {% endblock %}
  <div class="{% block container_size %}container{% endblock %} {% block extra_container_class %}{% endblock %}">
    {% block content  %}
    {% endblock content %}
  </div>
  <div class="footer d-flex flex-row align-items-center">
    <a class="card ms-3" href="{% url 'games:home' %}">
      <img loading="lazy" class="footer-logo" src="{% static 'img/logos/asobi.png' %}">
    </a>
    <div class="footer-info ms-2 me-auto">
      <h1>Asobi</h1>
      <p>bitgato</p>
      <p>MIT LICENSE</p>
    </div>
    <a class="card rounded-circle" href="{% url 'games:tictactoe' %}" data-toggle="tooltip" data-placement="top" title="Tic-Tac-Toe">
      <img loading="lazy" class="rounded-circle" src="{% static 'img/logos/tictactoe.png' %}">
    </a>
    <a class="card rounded-circle" href="{% url 'games:obstruction' %}" data-toggle="tooltip" data-placement="top" title="Obstruction">
      <img loading="lazy" class="rounded-circle" src="{% static 'img/logos/obstruction.png' %}">
    </a>
    <a class="card rounded-circle" href="{% url 'games:ludo' %}" data-toggle="tooltip" data-placement="top" title="Ludo">
      <img loading="lazy" class="rounded-circle" src="{% static 'img/logos/ludo.png' %}">
    </a>
    <a class="card rounded-circle" href="{% url 'games:battleship' %}" data-toggle="tooltip" data-placement="top" title="Battleship">
      <img loading="lazy" class="rounded-circle" src="{% static 'img/logos/battleship.png' %}">
    </a>
    <a class="card rounded-circle" href="{% url 'games:connect4' %}" data-toggle="tooltip" data-placement="top" title="Connect Four">
      <img loading="lazy" class="rounded-circle" src="{% static 'img/logos/connect4.png' %}">
    </a>
    <a class="card rounded-circle" href="{% url 'games:othello' %}" data-toggle="tooltip" data-placement="top" title="Othello">
      <img loading="lazy" class="rounded-circle" src="{% static 'img/logos/othello.png' %}">
    </a>
    <a class="card ms-auto me-3" href="https://github.com/bitgato/asobi">
      <img loading="lazy" class="footer-logo" src="{% static 'img/logos/github.png' %}">
    </a>
  </div>
</body>

</html>

templates/connect4.html
{% extends "game.html" %}
{% load render_bundle from webpack_loader %}
{% block head_title %}Asobi ({{request.user.username}}) - Connect Four{% endblock %}
{% block page_heading %}Connect Four{% endblock %}
{% block render %}
{% render_bundle 'connect4' %}
{% endblock %}

templates/obstruction.html
{% extends "game.html" %}
{% load render_bundle from webpack_loader %}
{% block head_title %}Asobi ({{request.user.username}}) - Obstruction{% endblock %}
{% block page_heading %}Obstruction{% endblock %}
{% block render %}
{% render_bundle 'obstruction' %}
{% endblock %}

templates/profile.html
{% extends "base.html" %}
{% load static %}
{% block head_title %}Asobi {% if request.user %}({{request.user.username}}){% endif %} - Profile{% endblock %}
{% block page_heading %}
{% if request.user == profile_user %}My{% else %}{{ profile_user.username }}'s{% endif %}
Profile
{% endblock %}
{% block content %}
{% for game_model in all_games_data %}
<div class="my-games mx-0 mb-5">
  <div class="my-games-heading d-flex flex-row justify-content-center">
    <div><img loading="lazy" class="game-table-logo" src="{% static game_model.logo %}"/></div>
    <a href="{% url game_model.page_url %}" class="game-table-heading ms-2">
      <h3>{{ game_model.display_name }}</h3>
    </a>
    <div class="game-table-heading ms-auto me-2">
      {% if request.user == profile_user %}
      <a href="{% url 'games:my_games_list' game_type=game_model.game_type %}">See more</a>
      {% else %}
      <a href="{% url 'games:user_games_list' game_type=game_model.game_type username=profile_user.username %}">See more</a>
      {% endif %}
    </div>
  </div>
  {% if game_model.game_model_data %}
  <table class="table table-responsive m-0">
    <thead class="thead-dark">
    <tr>
      <th>#</th>
      <th>Game code</th>
      <th>Opponents</th>
      <th>Result</th>
    </tr>
    </thead>
    <tbody>
    {% for game_data in game_model.game_model_data %}
    {% with game_data.game as game %}
    <tr>
      <th style="width: 8%" scope="row">{{game.id}}</th>
      <td>
        <a class="game-code-p ms-2 me-2 mb-0" href="{{ game_data.url }}">
          <code class="game-table-code">{{ game.game_code }}</code>
        </a>
      </td>
      <td>
        <div class="d-flex flex-row">
          {% for player in game_data.players %}
          <div class="game-table-opponent">{{ player|truncatechars:7 }}</div>
          {% empty %}
          <div class="no-opponents">None</div>
          {% endfor %}
        </div>
      </td>
      <td>
        {% if game.completed %}
        {% if not game.winner %}
        <div class="game-table-tie m-0 p-0">Tie</div>
        {% elif game.winner == profile_user %}
        <div class="game-table-win m-0 p-0">Win</div>
        {% else %}
        <div class="game-table-lost m-0 p-0">Loss</div>
        {% endif %}
        {% else %}
        <div class="game-table-ongoing m-0 p-0">Ongoing</div>
        {% endif %}
      </td>
    </tr>
    {% endwith %}
    {% endfor %}
    </tbody>
  </table>
  {% else %}
  <div class="no-games pt-2 mb-2 d-flex justify-content-center align-items-baseline w-100">
    {% if request.user == profile_user %}
    You have not played any {{ game_model.display_name }} games yet
    <a class="ms-2 small" href="{% url game_model.page_url %}"><u>Play now</u></a>
    {% else %}
    {{ profile_user.username }} has not played any {{ game_model.display_name }} games yet
    {% endif %}
  </div>
  {% endif %}
</div>
{% endfor %}
{% endblock %}